package com.metro.entity;

import java.math.BigDecimal;

public class YlOptionConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YL_OPTION_CONFIG.ID
     *
     * @mbggenerated
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YL_OPTION_CONFIG.CODE_GROUP
     *
     * @mbggenerated
     */
    private String codeGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YL_OPTION_CONFIG.CODE_CODE
     *
     * @mbggenerated
     */
    private String codeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YL_OPTION_CONFIG.CODE_VALUE
     *
     * @mbggenerated
     */
    private String codeValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YL_OPTION_CONFIG.CODE_COMMENT
     *
     * @mbggenerated
     */
    private String codeComment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YL_OPTION_CONFIG.ID
     *
     * @return the value of YL_OPTION_CONFIG.ID
     *
     * @mbggenerated
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YL_OPTION_CONFIG.ID
     *
     * @param id the value for YL_OPTION_CONFIG.ID
     *
     * @mbggenerated
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YL_OPTION_CONFIG.CODE_GROUP
     *
     * @return the value of YL_OPTION_CONFIG.CODE_GROUP
     *
     * @mbggenerated
     */
    public String getCodeGroup() {
        return codeGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YL_OPTION_CONFIG.CODE_GROUP
     *
     * @param codeGroup the value for YL_OPTION_CONFIG.CODE_GROUP
     *
     * @mbggenerated
     */
    public void setCodeGroup(String codeGroup) {
        this.codeGroup = codeGroup == null ? null : codeGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YL_OPTION_CONFIG.CODE_CODE
     *
     * @return the value of YL_OPTION_CONFIG.CODE_CODE
     *
     * @mbggenerated
     */
    public String getCodeCode() {
        return codeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YL_OPTION_CONFIG.CODE_CODE
     *
     * @param codeCode the value for YL_OPTION_CONFIG.CODE_CODE
     *
     * @mbggenerated
     */
    public void setCodeCode(String codeCode) {
        this.codeCode = codeCode == null ? null : codeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YL_OPTION_CONFIG.CODE_VALUE
     *
     * @return the value of YL_OPTION_CONFIG.CODE_VALUE
     *
     * @mbggenerated
     */
    public String getCodeValue() {
        return codeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YL_OPTION_CONFIG.CODE_VALUE
     *
     * @param codeValue the value for YL_OPTION_CONFIG.CODE_VALUE
     *
     * @mbggenerated
     */
    public void setCodeValue(String codeValue) {
        this.codeValue = codeValue == null ? null : codeValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YL_OPTION_CONFIG.CODE_COMMENT
     *
     * @return the value of YL_OPTION_CONFIG.CODE_COMMENT
     *
     * @mbggenerated
     */
    public String getCodeComment() {
        return codeComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YL_OPTION_CONFIG.CODE_COMMENT
     *
     * @param codeComment the value for YL_OPTION_CONFIG.CODE_COMMENT
     *
     * @mbggenerated
     */
    public void setCodeComment(String codeComment) {
        this.codeComment = codeComment == null ? null : codeComment.trim();
    }
}