package com.metro.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class YlOptionConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table YL_OPTION_CONFIG
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table YL_OPTION_CONFIG
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table YL_OPTION_CONFIG
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YL_OPTION_CONFIG
     *
     * @mbggenerated
     */
    public YlOptionConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YL_OPTION_CONFIG
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YL_OPTION_CONFIG
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YL_OPTION_CONFIG
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YL_OPTION_CONFIG
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YL_OPTION_CONFIG
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YL_OPTION_CONFIG
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YL_OPTION_CONFIG
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YL_OPTION_CONFIG
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YL_OPTION_CONFIG
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YL_OPTION_CONFIG
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table YL_OPTION_CONFIG
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(BigDecimal value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(BigDecimal value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(BigDecimal value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(BigDecimal value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<BigDecimal> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<BigDecimal> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCodeGroupIsNull() {
            addCriterion("CODE_GROUP is null");
            return (Criteria) this;
        }

        public Criteria andCodeGroupIsNotNull() {
            addCriterion("CODE_GROUP is not null");
            return (Criteria) this;
        }

        public Criteria andCodeGroupEqualTo(String value) {
            addCriterion("CODE_GROUP =", value, "codeGroup");
            return (Criteria) this;
        }

        public Criteria andCodeGroupNotEqualTo(String value) {
            addCriterion("CODE_GROUP <>", value, "codeGroup");
            return (Criteria) this;
        }

        public Criteria andCodeGroupGreaterThan(String value) {
            addCriterion("CODE_GROUP >", value, "codeGroup");
            return (Criteria) this;
        }

        public Criteria andCodeGroupGreaterThanOrEqualTo(String value) {
            addCriterion("CODE_GROUP >=", value, "codeGroup");
            return (Criteria) this;
        }

        public Criteria andCodeGroupLessThan(String value) {
            addCriterion("CODE_GROUP <", value, "codeGroup");
            return (Criteria) this;
        }

        public Criteria andCodeGroupLessThanOrEqualTo(String value) {
            addCriterion("CODE_GROUP <=", value, "codeGroup");
            return (Criteria) this;
        }

        public Criteria andCodeGroupLike(String value) {
            addCriterion("CODE_GROUP like", value, "codeGroup");
            return (Criteria) this;
        }

        public Criteria andCodeGroupNotLike(String value) {
            addCriterion("CODE_GROUP not like", value, "codeGroup");
            return (Criteria) this;
        }

        public Criteria andCodeGroupIn(List<String> values) {
            addCriterion("CODE_GROUP in", values, "codeGroup");
            return (Criteria) this;
        }

        public Criteria andCodeGroupNotIn(List<String> values) {
            addCriterion("CODE_GROUP not in", values, "codeGroup");
            return (Criteria) this;
        }

        public Criteria andCodeGroupBetween(String value1, String value2) {
            addCriterion("CODE_GROUP between", value1, value2, "codeGroup");
            return (Criteria) this;
        }

        public Criteria andCodeGroupNotBetween(String value1, String value2) {
            addCriterion("CODE_GROUP not between", value1, value2, "codeGroup");
            return (Criteria) this;
        }

        public Criteria andCodeCodeIsNull() {
            addCriterion("CODE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andCodeCodeIsNotNull() {
            addCriterion("CODE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCodeCodeEqualTo(String value) {
            addCriterion("CODE_CODE =", value, "codeCode");
            return (Criteria) this;
        }

        public Criteria andCodeCodeNotEqualTo(String value) {
            addCriterion("CODE_CODE <>", value, "codeCode");
            return (Criteria) this;
        }

        public Criteria andCodeCodeGreaterThan(String value) {
            addCriterion("CODE_CODE >", value, "codeCode");
            return (Criteria) this;
        }

        public Criteria andCodeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CODE_CODE >=", value, "codeCode");
            return (Criteria) this;
        }

        public Criteria andCodeCodeLessThan(String value) {
            addCriterion("CODE_CODE <", value, "codeCode");
            return (Criteria) this;
        }

        public Criteria andCodeCodeLessThanOrEqualTo(String value) {
            addCriterion("CODE_CODE <=", value, "codeCode");
            return (Criteria) this;
        }

        public Criteria andCodeCodeLike(String value) {
            addCriterion("CODE_CODE like", value, "codeCode");
            return (Criteria) this;
        }

        public Criteria andCodeCodeNotLike(String value) {
            addCriterion("CODE_CODE not like", value, "codeCode");
            return (Criteria) this;
        }

        public Criteria andCodeCodeIn(List<String> values) {
            addCriterion("CODE_CODE in", values, "codeCode");
            return (Criteria) this;
        }

        public Criteria andCodeCodeNotIn(List<String> values) {
            addCriterion("CODE_CODE not in", values, "codeCode");
            return (Criteria) this;
        }

        public Criteria andCodeCodeBetween(String value1, String value2) {
            addCriterion("CODE_CODE between", value1, value2, "codeCode");
            return (Criteria) this;
        }

        public Criteria andCodeCodeNotBetween(String value1, String value2) {
            addCriterion("CODE_CODE not between", value1, value2, "codeCode");
            return (Criteria) this;
        }

        public Criteria andCodeValueIsNull() {
            addCriterion("CODE_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andCodeValueIsNotNull() {
            addCriterion("CODE_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andCodeValueEqualTo(String value) {
            addCriterion("CODE_VALUE =", value, "codeValue");
            return (Criteria) this;
        }

        public Criteria andCodeValueNotEqualTo(String value) {
            addCriterion("CODE_VALUE <>", value, "codeValue");
            return (Criteria) this;
        }

        public Criteria andCodeValueGreaterThan(String value) {
            addCriterion("CODE_VALUE >", value, "codeValue");
            return (Criteria) this;
        }

        public Criteria andCodeValueGreaterThanOrEqualTo(String value) {
            addCriterion("CODE_VALUE >=", value, "codeValue");
            return (Criteria) this;
        }

        public Criteria andCodeValueLessThan(String value) {
            addCriterion("CODE_VALUE <", value, "codeValue");
            return (Criteria) this;
        }

        public Criteria andCodeValueLessThanOrEqualTo(String value) {
            addCriterion("CODE_VALUE <=", value, "codeValue");
            return (Criteria) this;
        }

        public Criteria andCodeValueLike(String value) {
            addCriterion("CODE_VALUE like", value, "codeValue");
            return (Criteria) this;
        }

        public Criteria andCodeValueNotLike(String value) {
            addCriterion("CODE_VALUE not like", value, "codeValue");
            return (Criteria) this;
        }

        public Criteria andCodeValueIn(List<String> values) {
            addCriterion("CODE_VALUE in", values, "codeValue");
            return (Criteria) this;
        }

        public Criteria andCodeValueNotIn(List<String> values) {
            addCriterion("CODE_VALUE not in", values, "codeValue");
            return (Criteria) this;
        }

        public Criteria andCodeValueBetween(String value1, String value2) {
            addCriterion("CODE_VALUE between", value1, value2, "codeValue");
            return (Criteria) this;
        }

        public Criteria andCodeValueNotBetween(String value1, String value2) {
            addCriterion("CODE_VALUE not between", value1, value2, "codeValue");
            return (Criteria) this;
        }

        public Criteria andCodeCommentIsNull() {
            addCriterion("CODE_COMMENT is null");
            return (Criteria) this;
        }

        public Criteria andCodeCommentIsNotNull() {
            addCriterion("CODE_COMMENT is not null");
            return (Criteria) this;
        }

        public Criteria andCodeCommentEqualTo(String value) {
            addCriterion("CODE_COMMENT =", value, "codeComment");
            return (Criteria) this;
        }

        public Criteria andCodeCommentNotEqualTo(String value) {
            addCriterion("CODE_COMMENT <>", value, "codeComment");
            return (Criteria) this;
        }

        public Criteria andCodeCommentGreaterThan(String value) {
            addCriterion("CODE_COMMENT >", value, "codeComment");
            return (Criteria) this;
        }

        public Criteria andCodeCommentGreaterThanOrEqualTo(String value) {
            addCriterion("CODE_COMMENT >=", value, "codeComment");
            return (Criteria) this;
        }

        public Criteria andCodeCommentLessThan(String value) {
            addCriterion("CODE_COMMENT <", value, "codeComment");
            return (Criteria) this;
        }

        public Criteria andCodeCommentLessThanOrEqualTo(String value) {
            addCriterion("CODE_COMMENT <=", value, "codeComment");
            return (Criteria) this;
        }

        public Criteria andCodeCommentLike(String value) {
            addCriterion("CODE_COMMENT like", value, "codeComment");
            return (Criteria) this;
        }

        public Criteria andCodeCommentNotLike(String value) {
            addCriterion("CODE_COMMENT not like", value, "codeComment");
            return (Criteria) this;
        }

        public Criteria andCodeCommentIn(List<String> values) {
            addCriterion("CODE_COMMENT in", values, "codeComment");
            return (Criteria) this;
        }

        public Criteria andCodeCommentNotIn(List<String> values) {
            addCriterion("CODE_COMMENT not in", values, "codeComment");
            return (Criteria) this;
        }

        public Criteria andCodeCommentBetween(String value1, String value2) {
            addCriterion("CODE_COMMENT between", value1, value2, "codeComment");
            return (Criteria) this;
        }

        public Criteria andCodeCommentNotBetween(String value1, String value2) {
            addCriterion("CODE_COMMENT not between", value1, value2, "codeComment");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table YL_OPTION_CONFIG
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table YL_OPTION_CONFIG
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}